table usuario {
  id_usuario int [primary key]
  primer_nombre varchar(300)
  segundo_nombre varchar(300)
  primer_apellido varchar(300)
  segundo_apellido varchar(300)
  correo_electronico varchar(300)
  salario_mensual numeric(30, 5)
  estado_usuario bool
}

table presupuesto {
  id_presupuesto int [primary key]
  id_usuario int
  nombre varchar(300)
  anio_inicio int
  mes_inicio int
  anio_fin int
  mes_fin int
  total_ingresos numeric(30, 5)
  total_gastos numeric(30, 5)
  total_ahorros numeric(30, 5)
  fecha_creacion datetime
  hora_creacion time
  estado_presupuesto bool
}

table categoria {
  id_categoria int [primary key]
  nombre varchar(300)
  descripcion_detallada varchar(300)
  tipo_categoria varchar(30)
}

table subcategoria {
  id_subcategoria int [primary key]
  id_categoria int
  nombre varchar(300)
  descripcion_detallada varchar(300)
  activo bool
  es_por_defecto int
}

table presupuesto_detalle {
  id_detalle int [primary key]
  id_presupuesto int
  id_subcategoria int
  monto_mensual_asignado numeric(30,5)
  observaciones varchar(300)
}

table obligacion_fija {
  id_obligacion int [primary key]
  id_subcategoria int
  nombre varchar(300)
  descripcion_detallada varchar(300)
  monto_fijo_mensual numeric(30,5)
  dia_vencimiento int
  vigente bool
  fecha_inicio datetime
  fecha_fin datetime
}

table transaccion {
  id_transaccion int [primary key]
  id_detalle int 
  anio_transaccion int
  mes_transaccion int
  id_obligacion int
  tipo_transaccion varchar(30)
  descripcion varchar(300)
  monto_transaccion numeric(30,5)
  fecha_transaccion datetime
  metodo_pago varchar(50)
  num_factura int
  observaciones varchar(300)
  fecha_registro datetime
  hora_registro time
}

table obligacionfija_transaccion {
  id_transaccion int 
  id_obligacion int
}

Ref: "usuario"."id_usuario" < "presupuesto"."id_usuario"

Ref: "presupuesto"."id_presupuesto" < "presupuesto_detalle"."id_presupuesto"

Ref: "categoria"."id_categoria" < "subcategoria"."id_categoria"

Ref: "subcategoria"."id_subcategoria" < "presupuesto_detalle"."id_subcategoria"

Ref: "subcategoria"."id_subcategoria" < "obligacion_fija"."id_subcategoria"

Ref: "presupuesto_detalle"."id_detalle" < "transaccion"."id_detalle"

Ref: "obligacion_fija"."id_obligacion" < "obligacionfija_transaccion"."id_transaccion"

Ref: "transaccion"."id_transaccion" < "obligacionfija_transaccion"."id_obligacion"